Create sum.py
anoopbhatn/LCC_MLRepo_Team2 pull request #6
Opened 2018-11-04 11:58 UTC by apoorvakumar1998

2018-11-05 19:12 UTC, anoopbhatn commented
1. Provide a proper description stating the changes done in the PR
2. Include the task name in the PR title
3. Please don't create a new branch/PR for every change. Push your changes to the same branch/PR

2018-11-05 19:17 UTC, anoopbhatn requested changes

2018-11-05 19:17 UTC, anoopbhatn commented on sum.py
> +sum=0;//variable to store sum
Leave a comment block about the file created date and author something like this :
'''
Created on October 22, 2018
@author: anoopbhatn
'''

After this, specify the purpose of the code in a comment block

2018-11-05 19:17 UTC, anoopbhatn commented on sum.py
> +start = int(input("Enter Start value:"))//inputing start value
Provide the comment line above the line about which you will be writing a comment. Something like : 
\# inputing start value  
start = int(input("Enter Start value:"))

2018-11-05 19:17 UTC, anoopbhatn commented on sum.py
> + for i in range(start,end+1)://for loop to determine sum
Write a comment block stating the purpose

2018-11-08 05:30 UTC, anoopbhatn requested changes

2018-11-08 05:30 UTC, anoopbhatn commented on sum.py
> -sum=0;//variable to store sum
Remove this file and push

git rm sum.py

git commit -m "Task-2 : Removed sum.py as a new file sum_range.py replaces the functionality of that"

git push -u origin <branch_name>

2018-11-08 05:30 UTC, anoopbhatn commented on sum_range.py
> + for i in range(start,end+1):
Will this work? Won't this throw wrong indentation error?

2018-11-08 05:30 UTC, anoopbhatn commented on sum_range.py
> +sum=sum + i
Also this. This should be inside the for loop right?

2018-11-08 06:20 UTC, anoopbhatn requested changes
The code looks good. Great job.
Can you put the file inside a folder named after you ?

2018-11-08 06:22 UTC, apoorvakumar1998 commented
how to do that?

On Thu, 8 Nov 2018, 11:50 am Anoop Bhat N <notifications@github.com wrote:

> *@anoopbhatn* requested changes on this pull request.
>
> The code looks good. Great job.
> Can you put the file inside a folder named after you ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/anoopbhatn/LCC_MLRepo_Team2/pull/6#pullrequestreview-172817730>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AeTB0qqhte6WJYZ83oqN1csWxVwRqq2Uks5us80ugaJpZM4YNQ0_>
> .
>

2018-11-08 06:25 UTC, anoopbhatn commented
Normal way. Just create a folder, put this code inside that. git add that folder. git rm the file outside and push.

2018-11-08 06:27 UTC, closed without merging